### Delete a estado
DELETE http://localhost:8080/cidades/4
Accept: application/json

### Delete estado, not found
DELETE http://localhost:8080/cidades/30
Accept: application/json

### Put cozinha, ok
PUT http://localhost:8080/cidades/2
Content-Type: application/json

{
  "nome": "Ribeirão Preto",
  "estado": {
    "id": 2
  }
}

### Put estado, bad request
PUT http://localhost:8080/cidades/2
Content-Type: application/json

{
  "nome": "Ribeirão Preto",
  "estado": {
    "id": 20
  }
}

### Put estado, not found
PUT http://localhost:8080/cidades/20
Content-Type: application/json

{
  "nome": "Ribeirão Preto",
  "estado": {
    "id": 2
  }
}

### Post estado, created
POST http://localhost:8080/cidades
Content-Type: application/json

{
  "nome": "Ribeirão Preto",
  "estado": {
    "id": 2
  }
}

### Post estado, bad request
POST http://localhost:8080/cidades
Content-Type: application/json

{
  "id": 1,
  "nome": "Ribeirão Preto",
  "estado": {
    "id": 10
  }
}

### Get a estado
GET http://localhost:8080/cidades/1
Accept: application/json

### Get a estado not found
GET http://localhost:8080/cidades/10
Accept: application/json

### Get all cidades
GET http://localhost:8080/cidades
Accept: application/json
