### Delete a estado
DELETE http://localhost:8080/cidades/4
Accept: application/vnd.food.v2+json

### Delete estado, not found
DELETE http://localhost:8080/cidades/30
Accept: application/vnd.food.v2+json

### Put cozinha, ok
PUT http://localhost:8080/cidades/2
Content-Type: application/vnd.food.v2+json

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 2
}

### Put estado, bad request
PUT http://localhost:8080/cidades/2
Content-Type: application/vnd.food.v2+json

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 20
}

### Put estado, not found
PUT http://localhost:8080/cidades/20
Content-Type: application/vnd.food.v2+json

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 2
}

### Post estado, created
POST http://localhost:8080/cidades
Content-Type: application/vnd.food.v2+json

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 2
}

### Post estado, bad request
POST http://localhost:8080/cidades
Content-Type: application/vnd.food.v2+json

{
  "idCidade": 1,
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 10
}

### Get a estado
GET http://localhost:8080/cidades/3
Accept: application/vnd.food.v2+json

### Get a estado not found
GET http://localhost:8080/cidades/10
Accept: application/vnd.food.v2+json

### Get all cidades
GET http://localhost:8080/cidades
Accept: application/vnd.food.v2+json
