POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZmF0dXJhbWVudG86ZmF0dXJhbWVudG8xMjM=

grant_type=client_credentials

###

POST http://localhost:8080/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZmF0dXJhbWVudG86ZmF0dXJhbWVudG8xMjM=

token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJSRUFEIiwiV1JJVEUiXSwiZXhwIjoxNjAzNjA5MzIxLCJhdXRob3JpdGllcyI6WyJHRVJBUl9SRUxBVE9SSU9TIiwiQ09OU1VMVEFSX1BFRElET1MiXSwianRpIjoidWYzb3Q1S3pGVzdiYVhIc0RHYW9GZE5DbjJJIiwiY2xpZW50X2lkIjoiZmF0dXJhbWVudG8ifQ.MqC72wGNVKRhiAxC2ImHr1Y3-b6RrO4seKkCI_Zi7BV_PpHuFy-Vf6KF3fli0rGukNHGsh7TmTbGn4oC0v0P5Z6hp7sAXSINyYbbdTEJFB-MSxeQ8QQzcuqSsAF-aKIPZv3vpJaa1mvPZPKcIbynJomveQ__peH07YcUP4RpTs7_ZJUP8908EJjra9VWefDb4ZutWq_37zr7PINx4oG2cEVrHNp4Jr6vv3tv5JUAC6o8bkWlyHvT2MCe-0J_g-0ld6iE5v1pH04T0q2WTOwDs7U6k6INm9MpEiv16-GtGogWRMwMZfJp7FJ2m4ZLJ4KpAlzt9psWsYwGLk1vmUrnrg

###
