### Delete one cozinhas
DELETE http://localhost:8080/cozinhas/3
Accept: application/json

### Delete one cozinhas notfoud
DELETE http://localhost:8080/cozinhas/30
Accept: application/json


### Put cozinha notfound
PUT http://localhost:8080/cozinhas/20
Content-Type: application/json

{"nome": "Brasileira"}

### Put cozinha, ok
PUT http://localhost:8080/cozinhas/2
Content-Type: application/json

{"nome": "Brasileira"}

### Post cozinha bad request
POST http://localhost:8080/cozinhas
Content-Type: application/json

{"nome": null}

### Post cozinha, created
POST http://localhost:8080/cozinhas
Content-Type: application/json

{"nome": "Brasileira"}

### Get one cozinhas not found
GET http://localhost:8080/cozinhas/10
Accept: application/json

### Get one cozinhas
GET http://localhost:8080/v1/cozinhas/1
Accept: application/json

### Get All cozinhas
GET http://localhost:8080/v1/cozinhas?size=2&page=1
Accept: application/json
Authorization: Bearer sM5k16exxlTeic7yt1_c5tcbMgw
