version: '3'

networks:
  minha-rede:
    driver: bridge

services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - minha-rede
    volumes:
      - ./mysql-datadir:/var/lib/mysql

#before run make build-mvn-app or make build-docker-app
  food-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rfaguiar/food-api:1.0.0
    command: /wait-for-it.sh mysql8:3306 -t 30 -- java --enable-preview -Duser.timezone=America/Sao_Paulo -Dserver.port=8080 -jar program.jar
#    container_name: food-api
    environment:
      DB_URL: "jdbc:mysql://mysql8:3306/food_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
      DB_USER: "root"
      DB_PASS: "my-secret-pw"
#    ports:
#      - "8080:8080"
    networks:
      - minha-rede
    depends_on:
      - mysql8
    deploy:
      replicas: 2
