version: '3'

networks:
  food-net:
    driver: bridge

services:
  food-mysql8:
    image: mysql:8
    container_name: food-mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3307:3306"
    networks:
      - food-net
    volumes:
      - ./mysql-datadir/temp:/var/lib/mysql


#before run make build-mvn-app or make build-docker-app
  food-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: rfaguiar/food-api:1.0.0
    command: /wait-for-it.sh food-mysql8:3306 -t 30 -- java --enable-preview -Duser.timezone=America/Sao_Paulo -Dserver.port=8080 -jar program.jar
    environment:
      DB_URL: "jdbc:mysql://food-mysql8:3306/food_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
      DB_USER: "root"
      DB_PASS: "my-secret-pw"
      SPRING_PROFILES_ACTIVE: dev
#    container_name: food-api
#    ports:
#      - "8080:8080"
    networks:
      - food-net
    depends_on:
      - food-mysql8
    deploy:
      replicas: 2

  food-nginx-proxy:
    build: ./nginx
    image: food-nginx-proxy
    container_name: food-nginx-proxy
    ports:
      - "80:80"
    networks:
      - food-net
    depends_on:
      - food-api
