FROM openjdk:15-jdk-slim as builder

WORKDIR /app

COPY . .

RUN ./mvnw clean dependency:list package

FROM openjdk:15-jdk-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar /app/program.jar
COPY ./cmd/wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh

ARG PORT=8080
ENV PORT=$PORT

EXPOSE $PORT

CMD java --enable-preview -Duser.timezone=America/Sao_Paulo -Dserver.port=$PORT -jar program.jar
