FROM openjdk:15-jdk-slim as builder

WORKDIR /app

COPY . .

RUN ./mvnw clean dependency:list install

FROM openjdk:15-jdk-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar /app/program.jar

ARG PORT=8080
ENV PORT=$PORT

EXPOSE $PORT

ENTRYPOINT java --enable-preview -Duser.timezone=America/Sao_Paulo -Dserver.port=$PORT -jar program.jar
