### um pedido
GET http://localhost:8080/pedidos/2
Accept: application/json

### pedido não encontrado
GET http://localhost:8080/pedidos/10
Accept: application/json

###

### todos pedidos
GET http://localhost:8080/pedidos
Accept: application/json

###

### criar pedido
POST http://localhost:8080/pedidos
Accept: application/json
Content-Type: application/json

{
  "restaurante": {
    "id": 1
  },
  "formaPagamento": {
    "id": 1
  },
  "enderecoEntrega": {
    "cep": "38400-000",
    "logradouro": "Rua Floriano Peixoto",
    "numero": "500",
    "complemento": "Apto 801",
    "bairro": "Brasil",
    "cidade": {
      "id": 1
    }
  },
  "itens": [
    {
      "produtoId": 1,
      "quantidade": 1
    },
    {
      "produtoId": 2,
      "quantidade": 2,
      "observacao": "Menos picante, por favor"
    }
  ]
}

### confirmação pedido
PUT http://localhost:8080/pedidos/1/confirmacao
Accept: application/json

###