### Delete one cozinhas
DELETE http://localhost:8080/cozinhas/3
Accept: application/json

### Put cozinha
PUT http://localhost:8080/cozinhas/2
Content-Type: application/json

{"nome": "Brasileira"}

### Post cozinha
POST http://localhost:8080/cozinhas
Content-Type: application/json

{"nome": "Brasileira"}

### Get all estados
GET http://localhost:8080/estados
Accept: application/json

### Get one cozinhas
GET http://localhost:8080/cozinhas/1
Accept: application/json

### Get one cozinhas xml
GET http://localhost:8080/cozinhas/1
Accept: application/xml

### Get All cozinhas
GET http://localhost:8080/cozinhas
Accept: application/json

### Get All cozinhas xml
GET http://localhost:8080/cozinhas
Accept: application/xml
