### Patch a restaurante, ok
PATCH http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 5
}

### Patch a restaurante, bad request
PATCH http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "cozinha": {
    "id": 10
  }
}

### Patch a restaurante, not found
PATCH http://localhost:8080/restaurantes/30
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": null
}

### Put a restaurante bad request
PUT http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Put a restaurante not found
PUT http://localhost:8080/restaurantes/30
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1,
    "nome": "lalalla"
  }
}

### Put a restaurante, ok
PUT http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}


### Put a restaurante, no content
DELETE http://localhost:8080/restaurantes/3/ativo

### Put a restaurante, no content
PUT http://localhost:8080/restaurantes/3/ativo

### Post a restaurante bad request
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "  ",
  "taxaFrete": -1,
  "cozinha": {
    "id": null
  }

}

### Post a restaurante bad request
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Post a restaurante, created
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}

### Get a restaurante
PUT http://localhost:8080/restaurantes/1/fechamento
Accept: application/json

### Get a restaurante not found
GET http://localhost:8080/restaurantes/10
Accept: application/json

### Get a restaurante
GET http://localhost:8080/restaurantes/1
Accept: application/json

### Get All restaurantes
GET http://localhost:8080/restaurantes
Accept: application/json

### DELETE para inativar lista de restaurantes
DELETE http://localhost:8080/restaurantes/ativacoes
Accept: application/json
Content-Type: application/json

[1, 30, 5]

### ATUALIZA para ativar lista de restaurantes
PUT http://localhost:8080/restaurantes/ativacoes
Accept: application/json
Content-Type: application/json

[1, 3, 5]

### Get All responsaveis do restaurante
GET http://localhost:8080/restaurantes/1/responsaveis
Accept: application/json

### DELETE para remover responsaveil do restaurante
DELETE http://localhost:8080/restaurantes/1/responsaveis/5
Accept: application/json

### ATUALIZA para associar responsaveil do restaurante
PUT http://localhost:8080/restaurantes/1/responsaveis/5
Accept: application/json

