### Patch a restaurante, ok
PATCH http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 5
}

### Patch a restaurante, bad request
PATCH http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "cozinha": {
    "id": 10
  }
}

### Patch a restaurante, not found
PATCH http://localhost:8080/restaurantes/30
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": null
}

### Put a restaurante bad request
PUT http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Put a restaurante not found
PUT http://localhost:8080/restaurantes/30
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}

### Put a restaurante
PUT http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}

### Post a restaurante bad request
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "  ",
  "taxaFrete": -1,
  "cozinha": {
    "id": null
  }

}

### Post a restaurante bad request
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Post a restaurante
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}

### Get a restaurante by nome e frete inicial e frete final
GET http://localhost:8080/restaurantes/por-nome-e-frete?nome=a&taxaFreteInicial=11&taxaFreteFinal=20
Accept: application/json

### Get a restaurante by nome e frete inicial
GET http://localhost:8080/restaurantes/por-nome-e-frete?nome=a&taxaFreteFinal=20

### Get a restaurante by nome e frete inicial
GET http://localhost:8080/restaurantes/por-nome-e-frete?nome=a&taxaFreteInicial=11
Accept: application/json

### Get a restaurante by nome
GET http://localhost:8080/restaurantes/por-nome-e-frete?nome=tuk
Accept: application/json

### Get all restaurante
GET http://localhost:8080/restaurantes/por-nome-e-frete
Accept: application/json

### Get a restaurante not found
GET http://localhost:8080/restaurantes/10
Accept: application/json

### Get a restaurante
GET http://localhost:8080/restaurantes/1
Accept: application/json

### Get All restaurantes
GET http://localhost:8080/restaurantes
Accept: application/json

###
