variable "prefix" {}
variable "db_url" {}
variable "db_port" {}
variable "db_username" {}
variable "db_password" {}
variable "db_name" {}
variable "s3_key" {}
variable "s3_secret" {}
variable "s3_bucket_name" {}
variable "s3_bucket_region" {}
variable "s3_folder" {}
variable "mail_host" {}
variable "mail_port" {}
variable "mail_user" {}
variable "mail_password" {}
variable "mail_remetente" {}
variable "jks_base64" {}
variable "jks_password" {}
variable "jks_alias" {}