variable "prefix" {}
variable "aws_region" {}
variable "bucket_name" {}
variable "cluster_name" {}
variable "cluster_instance_type" {}
variable "vpc_cidr_block" {}
variable "db_port" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "jks_alias" {}
variable "jks_base64" {}
variable "jks_password" {}
variable "mail_host" {}
variable "mail_password" {}
variable "mail_port" {}
variable "mail_remetente" {}
variable "mail_user" {}
variable "s3_user_key" {}
variable "s3_user_secret" {}
variable "domain_name" {}
variable "max_containers" {}
variable "min_containers" {}
variable "container_port" {}
variable "container_image_version" {}
variable "s3_folder" {}
