###

POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC1iYWNrZW5kOmJhY2tlbmQxMjM=

grant_type=client_credentials&scope=READ

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}

###

POST http://localhost:8080/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC1iYWNrZW5kOmJhY2tlbmQxMjM=
Accept: */*

token={{auth_token}}

###

POST http://localhost:8080/oauth2/revoke
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC1iYWNrZW5kOmJhY2tlbmQxMjM=

token={{auth_token}}


###