POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

username=manoel.loja@gmail.com&password=123&grant_type=password

###

POST http://localhost:8080/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz
Accept: */*

token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo1LCJ1c2VyX25hbWUiOiJtYW5vZWwubG9qYUBnbWFpbC5jb20iLCJzY29wZSI6WyJSRUFEIiwiV1JJVEUiXSwiZXhwIjoxNjAzNTg3NjI4LCJqdGkiOiJYRVcyTk9yRFdYdGdUTEwyTWRwdzJYakZZTjQiLCJub21lX2NvbXBsZXRvIjoiTWFub2VsIExpbWEiLCJjbGllbnRfaWQiOiJmb29kLXdlYiJ9.IHHlWM85ZadqshUGym-XSPNyw983ObBTK_pNVduE2gHJQCtZYu4a_-C9uYJK_fSroSJ0z9xdFFv5ilEHF9XunWdvObADmRAtXebuOVYnPZEDpySV2mWcpD2HkMX3W4bxvAYwhkdr8TkcqxKouqUr_epgVukGWYfWfB0sCqK2HDLzdTJJw5qfuiCJn525qTrZVPJiivVPiFWtVouydaADfVm1VOmTmIhDHL2BMIghERICCk-DhKrifUq_WQ9QKpiG03TB0lMKwtoqCjUgiDkChYrFnlPH108HSXxIWBE20NISPJtEcAG0TE6-3YV0xymEK0C-Ecw3gGohUx0MVDVc1Q

###

POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

refresh_token=DRVHbUlSQ_ZNo6pbjChY0j_t_zA&grant_type=refresh_token

###