POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

username=manoel.loja@gmail.com&password=123&grant_type=password

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}

###

POST http://localhost:8080/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz
Accept: */*

token={{auth_token}}

###

POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

refresh_token={{auth_refresh_token}}&grant_type=refresh_token

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}
###