apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: food-api
  namespace: dev-to
spec:
  selector:
    matchLabels:
      app: food-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: food-api
    spec:
      containers:
        - image: rfaguiar/food-api
          name: food-api
          env:
            # Use secret in real usage
            - name: DB_URL
              value: 'jdbc:mysql://mysql:3306/food_db?createDatabaseIfNotExist=true&serverTimezone=UTC'
            - name: DB_USER
              value: myapp
            - name: DB_PASS
              value: myapp_pwd
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: food-api
  namespace: dev-to
spec:
  ports:
    - port: 8080
  selector:
    app: food-api
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-api
  namespace: dev-to
spec:
  rules:
    - host: dev.food-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: food-api
                port:
                  number: 8080
