apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dev-to
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root_pwd
            - name: MYSQL_USER
              value: myapp
            - name: MYSQL_PASSWORD
              value: myapp_pwd
            - name: MYSQL_DATABASE
              value: food_db
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dev-to
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
