### Delete a estado
DELETE {{base_host}}/cidades/4
Accept: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

### Delete estado, not found
DELETE {{base_host}}/cidades/30
Accept: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

### Put cozinha, ok
PUT {{base_host}}/cidades/2
Content-Type: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 2
}

### Put estado, bad request
PUT {{base_host}}/cidades/2
Content-Type: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 20
}

### Put estado, not found
PUT {{base_host}}/cidades/20
Content-Type: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 2
}

### Post estado, created
POST {{base_host}}/cidades
Content-Type: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

{
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 2
}

### Post estado, bad request
POST {{base_host}}/cidades
Content-Type: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

{
  "idCidade": 1,
  "nomeCidade": "Ribeirão Preto",
  "idEstado": 10
}

### Get a estado
GET {{base_host}}/cidades/3
Accept: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

### Get a estado not found
GET {{base_host}}/cidades/10
Accept: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}

### Get all cidades
GET {{base_host}}/cidades
Accept: application/vnd.food.v2+json
Authorization: Bearer {{auth_token}}
