### Delete one cozinhas
DELETE {{base_host}}/cozinhas/3
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete one cozinhas notfoud
DELETE {{base_host}}/cozinhas/30
Accept: application/json
Authorization: Bearer {{auth_token}}


### Put cozinha notfound
PUT {{base_host}}/cozinhas/20
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": "Brasileira"}

### Put cozinha, ok
PUT {{base_host}}/cozinhas/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": "Brasileira"}

### Post cozinha bad request
POST {{base_host}}/cozinhas
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": null}

### Post cozinha, created
POST {{base_host}}/cozinhas
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": "Brasileira"}

### Get one cozinhas not found
GET {{base_host}}/cozinhas/10
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get one cozinhas
GET {{base_host}}/v1/cozinhas/1
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get All cozinhas
GET {{base_host}}/v1/cozinhas?size=2&page=1
Accept: application/json
Authorization: Bearer {{auth_token}}
