### Delete a estado
DELETE {{base_host}}/estados/4
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete a estado, conflict
DELETE {{base_host}}/estados/3
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete estado, not not found
DELETE {{base_host}}/estados/30
Accept: application/json
Authorization: Bearer {{auth_token}}

### Put cozinha, ok
PUT {{base_host}}/estados/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": "Rio de Janeiro"}

### Put estado, bad request
PUT {{base_host}}/estados/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": null}

### Put estado, not found
PUT {{base_host}}/estados/20
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": "Rio de Janeiro"}

### Post estado, created
POST {{base_host}}/estados
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"nome": "Natal"}

### Post estado, bad request
POST {{base_host}}/estados
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{"id": 1, "nome": null}

### Get a estado
GET {{base_host}}/estados/1
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get a estado not found
GET {{base_host}}/estados/10
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get all estados
GET {{base_host}}/estados
Accept: application/json
Authorization: Bearer {{auth_token}}
