GET {{base_host}}/estatisticas/vendas-diarias
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{base_host}}/estatisticas/vendas-diarias
Accept: application/pdf, application/json
Authorization: Bearer {{auth_token}}

###
