

###
DELETE {{base_host}}/grupos/1/permissoes/1
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{base_host}}/usuarios/1/grupos
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{base_host}}/grupos/1/permissoes
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{base_host}}/grupos/1
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{base_host}}/grupos
Accept: application/json
Authorization: Bearer {{auth_token}}