### um pedido
GET {{base_host}}/pedidos/f9981ca4-5a5e-4da3-af04-933861df3e55
Accept: application/json
Authorization: Bearer {{auth_token}}

### todos pedidos
GET {{base_host}}/pedidos?page=2
Accept: application/json
Authorization: Bearer {{auth_token}}

### confirmação pedido
PUT {{base_host}}/pedidos/f9981ca4-5a5e-4da3-af04-933861df3e55/confirmacao
Accept: application/json
Authorization: Bearer {{auth_token}}

### cancelamento pedido
PUT {{base_host}}/pedidos/f9981ca4-5a5e-4da3-af04-933861df3e55/cancelamento
Accept: application/json
Authorization: Bearer {{auth_token}}

### entrega pedido
PUT {{base_host}}/pedidos/6f49ede5-cb9c-4bfd-ba22-26ed1e891237/entrega
Accept: application/json
Authorization: Bearer {{auth_token}}

### pedido não encontrado
GET {{base_host}}/pedidos/6f49ede5-cb9c-4bfd-ba22-26ed1e8912370
Accept: application/json
Authorization: Bearer {{auth_token}}

### criar pedido
POST {{base_host}}/pedidos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "restaurante": {
    "id": 1
  },
  "formaPagamento": {
    "id": 1
  },
  "enderecoEntrega": {
    "cep": "38400-000",
    "logradouro": "Rua Floriano Peixoto",
    "numero": "500",
    "complemento": "Apto 801",
    "bairro": "Brasil",
    "cidade": {
      "id": 1
    }
  },
  "itens": [
    {
      "produtoId": 1,
      "quantidade": 1
    },
    {
      "produtoId": 2,
      "quantidade": 2,
      "observacao": "Menos picante, por favor"
    }
  ]
}

### um pedido criado
GET {{base_host}}/pedidos/6f49ede5-cb9c-4bfd-ba22-26ed1e891237
Accept: application/json
Authorization: Bearer {{auth_token}}
