### Patch a restaurante, ok
PATCH {{base_host}}/restaurantes/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineira",
  "taxaFrete": 5
}

### Patch a restaurante, bad request
PATCH {{base_host}}/restaurantes/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineira",
  "cozinha": {
    "id": 10
  }
}

### Patch a restaurante, not found
PATCH {{base_host}}/restaurantes/30
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineira",
  "taxaFrete": null
}

### Put a restaurante bad request
PUT {{base_host}}/restaurantes/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Put a restaurante not found
PUT {{base_host}}/restaurantes/30
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1,
    "nome": "lalalla"
  }
}

### Put a restaurante, ok
PUT {{base_host}}/restaurantes/3
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}


### Put a restaurante, no content
DELETE {{base_host}}/restaurantes/3/ativo
Authorization: Bearer {{auth_token}}

### Put a restaurante, no content
PUT {{base_host}}/restaurantes/3/ativo
Authorization: Bearer {{auth_token}}

### Post a restaurante bad request
POST {{base_host}}/restaurantes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "  ",
  "taxaFrete": -1,
  "cozinha": {
    "id": null
  }

}

### Post a restaurante bad request
POST {{base_host}}/restaurantes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Post a restaurante, created
POST {{base_host}}/restaurantes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}

### Get a fechar restaurante
PUT {{base_host}}/restaurantes/1/fechamento
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get a formas pagamento de um restaurante
GET {{base_host}}/restaurantes/1/formas-pagamento
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get produtos de um restaurante
GET {{base_host}}/restaurantes/1/produtos
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get produto de um restaurante
GET {{base_host}}/restaurantes/1/produtos/1
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get produtos de um restaurante
GET {{base_host}}/restaurantes/1/produtos/1/foto
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get a restaurante not found
GET {{base_host}}/restaurantes/10
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get a restaurante
GET {{base_host}}/restaurantes/1
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get All restaurantes
GET {{base_host}}/restaurantes
Accept: application/json
Authorization: Bearer {{auth_token}}

### DELETE para inativar lista de restaurantes
DELETE {{base_host}}/restaurantes/ativacoes
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[1, 30, 5]

### ATUALIZA para ativar lista de restaurantes
PUT {{base_host}}/restaurantes/ativacoes
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[1, 3, 5]

### Get All responsaveis do restaurante
GET {{base_host}}/restaurantes/1/responsaveis
Accept: application/json
Authorization: Bearer {{auth_token}}

### DELETE para remover responsaveil do restaurante
DELETE {{base_host}}/restaurantes/1/responsaveis/5
Accept: application/json
Authorization: Bearer {{auth_token}}

### ATUALIZA para associar responsaveil do restaurante
PUT {{base_host}}/restaurantes/1/responsaveis/5
Accept: application/json
Authorization: Bearer {{auth_token}}

### ATUALIZA para associar responsaveil do restaurante
PUT {{base_host}}/restaurantes/3/abertura
Accept: application/json
Authorization: Bearer {{auth_token}}

### ATUALIZA para associar responsaveil do restaurante
PUT {{base_host}}/restaurantes/1/fechamento
Accept: application/json
Authorization: Bearer {{auth_token}}

