### Patch a restaurante, ok
PATCH http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 5
}

### Patch a restaurante, bad request
PATCH http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "cozinha": {
    "id": 10
  }
}

### Patch a restaurante, not found
PATCH http://localhost:8080/restaurantes/30
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": null
}

### Put a restaurante bad request
PUT http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Put a restaurante not found
PUT http://localhost:8080/restaurantes/30
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1,
    "nome": "lalalla"
  }
}

### Put a restaurante, ok
PUT http://localhost:8080/restaurantes/3
Content-Type: application/json

{
  "nome": "Comida Mineira",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}


### Put a restaurante, no content
DELETE http://localhost:8080/restaurantes/3/ativo

### Put a restaurante, no content
PUT http://localhost:8080/restaurantes/3/ativo

### Post a restaurante bad request
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "  ",
  "taxaFrete": -1,
  "cozinha": {
    "id": null
  }

}

### Post a restaurante bad request
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 10
  }
}

### Post a restaurante, created
POST http://localhost:8080/restaurantes
Content-Type: application/json

{
  "nome": "Comida Mineiraaa",
  "taxaFrete": 12,
  "cozinha": {
    "id": 1
  }
}

### Get a fechar restaurante
PUT http://localhost:8080/restaurantes/1/fechamento
Accept: application/json

### Get a formas pagamento de um restaurante
GET http://localhost:8080/restaurantes/1/formas-pagamento
Accept: application/json

### Get produtos de um restaurante
GET http://localhost:8080/restaurantes/1/produtos
Accept: application/json

### Get produto de um restaurante
GET http://localhost:8080/restaurantes/1/produtos/1
Accept: application/json

### Get produtos de um restaurante
GET http://localhost:8080/restaurantes/1/produtos/1/foto
Accept: application/json

### Get a restaurante not found
GET http://localhost:8080/restaurantes/10
Accept: application/json

### Get a restaurante
GET http://localhost:8080/restaurantes/1
Accept: application/json

### Get All restaurantes
GET http://localhost:8080/restaurantes
Accept: application/json

### DELETE para inativar lista de restaurantes
DELETE http://localhost:8080/restaurantes/ativacoes
Accept: application/json
Content-Type: application/json

[1, 30, 5]

### ATUALIZA para ativar lista de restaurantes
PUT http://localhost:8080/restaurantes/ativacoes
Accept: application/json
Content-Type: application/json

[1, 3, 5]

### Get All responsaveis do restaurante
GET http://localhost:8080/restaurantes/1/responsaveis
Accept: application/json

### DELETE para remover responsaveil do restaurante
DELETE http://localhost:8080/restaurantes/1/responsaveis/5
Accept: application/json

### ATUALIZA para associar responsaveil do restaurante
PUT http://localhost:8080/restaurantes/1/responsaveis/5
Accept: application/json

### ATUALIZA para associar responsaveil do restaurante
PUT http://localhost:8080/v1/restaurantes/3/abertura
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo1LCJ1c2VyX25hbWUiOiJtYW5vZWwubG9qYUBnbWFpbC5jb20iLCJzY29wZSI6WyJXUklURSIsIlJFQUQiXSwiZXhwIjoxNjAzMjQyOTA5LCJqdGkiOiJHRVNpeEl6VDBqcmxpemVmS0dTRlNjVUl5cG8iLCJub21lX2NvbXBsZXRvIjoiTWFub2VsIExpbWEiLCJjbGllbnRfaWQiOiJmb29kLXdlYiJ9.CQ1jZ7lSpvq2Ormg8BPmTBJHdWOCGaRLsHJte52w_ysOZeODn0GdAgQGz5BjJhdInj_eh43PFuS8ujSZLTjQsSp5fn_hvmQFnOTi7gg2IJ9Z_ArBlhBK88djbh_PLKZB5gZYXy4TcnSWrG3BUo59mk2ulaG-9t_hgbbb6xeCsB6PMXfvMmoMRoSbfOzbcxCq6sJvZsbkwP01NlplYxGdtuh2oQNxPXuIUzi0aW5V7ca8qh1XWQGu_s4nDNQE_enlv9qMziQewATtsG9ljwJTZDkyRCESvGaGfXevilEdUT-pkvqvXt0ereptdi4VhZOOsh5os5GfulNGbSFFQ0z7Xg

### ATUALIZA para associar responsaveil do restaurante
PUT http://localhost:8080/v1/restaurantes/1/fechamento
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjo1LCJ1c2VyX25hbWUiOiJtYW5vZWwubG9qYUBnbWFpbC5jb20iLCJzY29wZSI6WyJXUklURSIsIlJFQUQiXSwiZXhwIjoxNjAzMjQyOTA5LCJqdGkiOiJHRVNpeEl6VDBqcmxpemVmS0dTRlNjVUl5cG8iLCJub21lX2NvbXBsZXRvIjoiTWFub2VsIExpbWEiLCJjbGllbnRfaWQiOiJmb29kLXdlYiJ9.CQ1jZ7lSpvq2Ormg8BPmTBJHdWOCGaRLsHJte52w_ysOZeODn0GdAgQGz5BjJhdInj_eh43PFuS8ujSZLTjQsSp5fn_hvmQFnOTi7gg2IJ9Z_ArBlhBK88djbh_PLKZB5gZYXy4TcnSWrG3BUo59mk2ulaG-9t_hgbbb6xeCsB6PMXfvMmoMRoSbfOzbcxCq6sJvZsbkwP01NlplYxGdtuh2oQNxPXuIUzi0aW5V7ca8qh1XWQGu_s4nDNQE_enlv9qMziQewATtsG9ljwJTZDkyRCESvGaGfXevilEdUT-pkvqvXt0ereptdi4VhZOOsh5os5GfulNGbSFFQ0z7Xg

