GET {{base_host}}/usuarios
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{base_host}}/usuarios/1
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{base_host}}/usuarios/5/grupos
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET {{base_host}}/restaurantes/1/responsaveis
Accept: application/json
Authorization: Bearer {{auth_token}}

###

DELETE {{base_host}}/usuarios/1/grupos/2
Accept: application/json
Authorization: Bearer {{auth_token}}

###


PUT {{base_host}}/usuarios/1/grupos/2
Accept: application/json
Authorization: Bearer {{auth_token}}

###

